{
 "title": "User API",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "System Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"otus\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"otus\", container!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Application Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "App latency, ms",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \n      sum by (le, exported_endpoint) \n         (rate(app_request_latency_seconds_bucket[1m]))\n) * 1000",
     "legendFormat": "{{ exported_endpoint }}, 0.5"
    },
    {
     "expr": "histogram_quantile(0.95, \n      sum by (le, exported_endpoint) \n         (rate(app_request_latency_seconds_bucket[1m]))\n) * 1000",
     "legendFormat": "{{ exported_endpoint }}, 0.95"
    },
    {
     "expr": "histogram_quantile(0.99, \n      sum by (le, exported_endpoint) \n         (rate(app_request_latency_seconds_bucket[1m]))\n) * 1000",
     "legendFormat": "{{ exported_endpoint }}, 0.99"
    },
    {
     "expr": "histogram_quantile(1.0, \n      sum by (le, exported_endpoint) \n         (rate(app_request_latency_seconds_bucket[1m]))\n) * 1000",
     "legendFormat": "{{ exported_endpoint }}, max"
    }
   ]
  },
  {
   "title": "App RPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_endpoint) (rate(app_request_count[1m]))",
     "legendFormat": "{{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "App Error Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_endpoint) (increase(app_request_count{status_code=~\"5.+\"}[1m]))",
     "legendFormat": "{{exported_endpoint}}"
    }
   ]
  },
  { "title": "Nginx Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Nginx latency, ms",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \n      sum by (le) \n         (rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"otusdemo\"}[1m]))\n) * 1000",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, \n      sum by (le) \n         (rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"otusdemo\"}[1m]))\n) * 1000",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, \n      sum by (le) \n         (rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"otusdemo\"}[1m]))\n) * 1000",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(1.0, \n      sum by (le) \n         (rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"otusdemo\"}[1m]))\n) * 1000",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Nginx RPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count[1m]))",
     "legendFormat": "rps"
    }
   ]
  },
  {
   "title": "Nginx Error Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\", exported_service=\"otusdemo\"}[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Database Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Active Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_count{state=\"active\", datname=\"otusdemo\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit{datname=\"otusdemo\"}[5m])",
     "legendFormat": "{{datname}} commits"
    },
    {
     "expr": "irate(pg_stat_database_xact_rollback{datname=\"otusdemo\"}[5m])",
     "legendFormat": "{{datname}} rollbacks"
    }
   ]
  },
  {
   "title": "Conflicts/Deadlocks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_conflicts{datname=\"otusdemo\"}[5m])",
     "legendFormat": "{{datname}} conflicts"
    },
    {
     "expr": "irate(pg_stat_database_deadlocks{datname=\"otusdemo\"}[5m])",
     "legendFormat": "{{datname}} deadlocks"
    }
   ]
  }
 ]
}